apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-persistent-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
  storageClassName: standard
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: container2-deployment
  labels:
    app: container2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: container2
  template:
    metadata:
      labels:
        app: container2
    spec:
      containers:
      - name: container2
        image: us-central1-docker.pkg.dev/k8s-hirva/kube-repo/container2:latest #image path
        imagePullPolicy: Always
        ports:
        - containerPort: 6001
        volumeMounts:
            - name: my-volume
              mountPath: "/hirva_PV_dir"
      volumes: 
        - name: my-volume
          persistentVolumeClaim:
            claimName: my-persistent-volume-claim
---
apiVersion: v1
kind: Service
metadata:
  name: container2-service
spec:
  selector:
    app: container2
  ports:
    - protocol: TCP
      port: 6001
      targetPort: 6001
